import assert from "node:assert/strict";
import test from "node:test";
import { renderHtmlPage } from "../renderers/renderHtml.js";
import { renderAdaptiveThemeInlineHtmlFragment } from "../renderers/renderAdaptiveThemeInlineHtml.js";
import { renderInlineHtmlFragment } from "../renderers/renderInlineHtml.js";
import { renderUpgradedInlineHtmlFragment } from "../renderers/renderUpgradedInlineHtml.js";
import type { AdaptiveThemeHtmlPageInput } from "../schemas/adaptiveThemeHtmlPageSchema.js";
import type { HtmlPageInput } from "../schemas/htmlPageSchema.js";
import type { UpgradedHtmlPageInput } from "../schemas/upgradedHtmlPageSchema.js";
import {
  renderInlineRichText,
  renderInlineRichTextParagraphs
} from "../utils/renderInlineRichText.js";

const samplePage: HtmlPageInput = {
  template: "article",
  title: "文本渲染回归",
  lang: "zh-CN",
  theme: "modern-blue",
  sections: [
    {
      type: "features",
      heading: "模型评价",
      items: [
        {
          title: "Gemma 4",
          body: "Gemma 4 在思考深度给满时可以跟彼时的 Claude Sonnet 掰手腕。\n写作场景推荐用 Gemini 2.5 Pro。"
        },
        {
          title: "Claude Sonnet 4.6",
          body: "    听得懂人话，提问能促使你深入思考。\n    缺点是文字本体风格过于浓烈。"
        }
      ]
    },
    {
      type: "content",
      heading: "正文",
      body: "第一段。\n\n第二段。"
    },
    {
      type: "faq",
      heading: "常见问题",
      items: [
        {
          question: "会保留显式换行吗？",
          answer: "第一行<br>第二行"
        }
      ]
    }
  ],
  footer: {
    text: "页脚第一行\n\n页脚第二行"
  }
};

const upgradedSamplePage: UpgradedHtmlPageInput = {
  title: "升级渲染回归",
  lang: "zh-CN",
  theme: "modern-blue",
  contentTypes: ["research", "compare"],
  tokens: {
    cardRadius: "large",
    shadowLevel: "soft"
  },
  blocks: [
    {
      type: "hero",
      title: "规则系统 + 设计令牌",
      subtitle: "用内容类型策略驱动页面结构。",
      meta: ["research", "compare"]
    },
    {
      type: "summary-card",
      title: "核心结论",
      body: "不要维护模板库，应维护规则系统。<script>alert(1)</script>",
      items: [
        {
          title: "稳定",
          body: "组件集合有限，输出更稳定。"
        }
      ]
    },
    {
      type: "comparison-table",
      title: "方案对比",
      columns: ["模板库", "规则系统"],
      rows: [
        {
          label: "维护成本",
          cells: ["高", "低"]
        }
      ]
    },
    {
      type: "source-list",
      title: "参考来源",
      items: [
        {
          label: "示例来源",
          href: "javascript:alert(1)",
          description: "非法链接不会渲染为可点击链接。"
        }
      ]
    }
  ],
  footer: {
    text: "Generated by upgraded renderer"
  }
};

const adaptiveNewsSamplePage: AdaptiveThemeHtmlPageInput = {
  title: "今日重要新闻",
  lang: "zh-CN",
  contentTypes: ["news"],
  styleProfile: "auto",
  blocks: [
    {
      type: "hero",
      eyebrow: "新闻速览",
      title: "旧报纸风格新闻页",
      subtitle: "自动匹配 news 内容类型，使用旧纸张色彩和宋体/仿宋一类衬线字体。"
    },
    {
      type: "summary-card",
      title: "核心摘要",
      body: "新闻内容应该呈现更接近报刊的视觉气质，同时继续安全转义 <script>alert(1)</script>。"
    }
  ],
  footer: {
    text: "Generated by adaptive renderer"
  }
};

test("renderInlineRichText merges soft line breaks into inline text", () => {
  assert.equal(
    renderInlineRichText("第一句。\n第二句。"),
    "第一句。 第二句。"
  );
});

test("renderInlineRichText creates paragraph blocks only for blank-line breaks", () => {
  assert.equal(
    renderInlineRichText("第一段。\n\n第二段。"),
    "<p>第一段。</p><p>第二段。</p>"
  );
});

test("renderInlineRichText preserves explicit br tags", () => {
  assert.equal(
    renderInlineRichText("第一行<br />第二行"),
    "第一行<br>第二行"
  );
});

test("renderInlineRichTextParagraphs trims indentation on each line", () => {
  assert.deepEqual(renderInlineRichTextParagraphs("    第一行。\n\t第二行。"), [
    "第一行。 第二行。"
  ]);
});

test("renderHtmlPage uses shared paragraph-aware rendering without nested p tags", async () => {
  const html = await renderHtmlPage(samplePage);

  assert.match(html, /Gemma 4 在思考深度给满时可以跟彼时的 Claude Sonnet 掰手腕。\s+写作场景推荐用 Gemini 2\.5\s+Pro。/);
  assert.doesNotMatch(html, /Gemma 4 在思考深度给满时可以跟彼时的 Claude Sonnet 掰手腕。<br>/);
  assert.match(html, /<div class="rich-text-group rich-text-panel">\s*<p>第一段。<\/p>\s*<p>第二段。<\/p>\s*<\/div>/);
  assert.doesNotMatch(html, /<p>\s*<p>/);
});

test("renderInlineHtmlFragment keeps the same paragraph semantics as full-page renderer", async () => {
  const html = await renderInlineHtmlFragment(samplePage);

  assert.match(html, /Gemma 4 在思考深度给满时可以跟彼时的 Claude Sonnet 掰手腕。\s+写作场景推荐用 Gemini 2\.5\s+Pro。/);
  assert.match(html, /第一行<br\s*\/?>第二行/);
  assert.match(
    html,
    /<div[^>]*>\s*<p[^>]*>\s*第一段。\s*<\/p>\s*<p[^>]*>\s*第二段。\s*<\/p>\s*<\/div>/
  );
  assert.doesNotMatch(html, /听得懂人话，提问能促使你深入思考。<\/p>\s*<p/);
});

test("renderUpgradedInlineHtmlFragment renders independent upgraded blocks safely", async () => {
  const html = await renderUpgradedInlineHtmlFragment(upgradedSamplePage);

  assert.match(html, /data-html-render-mcp="upgraded-inline"/);
  assert.match(html, /data-content-types="research,compare"/);
  assert.match(html, /data-block-type="summary-card"/);
  assert.match(html, /规则系统 \+ 设计令牌/);
  assert.match(html, /&lt;script&gt;alert\(1\)&lt;\/script&gt;/);
  assert.match(html, /方案对比/);
  assert.doesNotMatch(html, /javascript:alert/);
});

test("renderAdaptiveThemeInlineHtmlFragment maps news to old newspaper styling", async () => {
  const html = await renderAdaptiveThemeInlineHtmlFragment(adaptiveNewsSamplePage);

  assert.match(html, /data-html-render-mcp="adaptive-theme-inline"/);
  assert.match(html, /data-content-types="news"/);
  assert.match(html, /data-style-profile="old-newspaper"/);
  assert.match(html, /Songti SC/);
  assert.match(html, /FangSong/);
  assert.match(html, /#fbf1d8/);
  assert.match(html, /&lt;script&gt;alert\(1\)&lt;\/script&gt;/);
});

test("renderAdaptiveThemeInlineHtmlFragment allows explicit style profile override", async () => {
  const html = await renderAdaptiveThemeInlineHtmlFragment({
    ...adaptiveNewsSamplePage,
    styleProfile: "academic-journal"
  });

  assert.match(html, /data-style-profile="academic-journal"/);
  assert.doesNotMatch(html, /data-style-profile="old-newspaper"/);
});
