import {
  articleAssemblyInputSchema,
  type ArticleDiagnostic,
  type ArticleSectionDraft
} from "../schemas/articleHtmlGenerationSchema.js";
import {
  informationStructureHtmlPageSchema,
  type InformationStructureHtmlPageInput
} from "../schemas/informationStructureHtmlPageSchema.js";
import { articleDiagnostic, hasBlockingDiagnostics } from "./shared.js";

function orderedSections(planSectionIds: string[], drafts: ArticleSectionDraft[]): ArticleSectionDraft[] {
  const draftById = new Map(drafts.map((draft) => [draft.sectionId, draft]));

  return planSectionIds
    .map((sectionId) => draftById.get(sectionId))
    .filter((draft): draft is ArticleSectionDraft => Boolean(draft));
}

export function assembleArticleHtmlPage(value: unknown): {
  page: InformationStructureHtmlPageInput;
  diagnostics: ArticleDiagnostic[];
  coverageSummary: {
    plannedSections: number;
    receivedSections: number;
    missingSectionIds: string[];
    uncoveredSourceItems: string[];
  };
  nextAction: "validate_html_render_page" | "revise_plan" | "revise_sections";
} {
  const { plan, sections } = articleAssemblyInputSchema.parse(value);
  const diagnostics: ArticleDiagnostic[] = [];
  const planSectionIds = plan.sections.map((section) => section.id);
  const receivedSectionIds = new Set(sections.map((section) => section.sectionId));
  const missingSectionIds = planSectionIds.filter((sectionId) => !receivedSectionIds.has(sectionId));
  const coveredSourceItems = new Set(sections.flatMap((section) => section.sourceCoverage));
  const plannedSourceItems = plan.sections.flatMap((section) => section.sourceCoverage);
  const uncoveredSourceItems = plannedSourceItems.filter((item) => !coveredSourceItems.has(item));

  missingSectionIds.forEach((sectionId) => {
    diagnostics.push(
      articleDiagnostic(
        "sections",
        "missing_section_draft",
        `Missing draft for planned section "${sectionId}".`,
        "Draft and validate this planned section before assembly."
      )
    );
  });

  uncoveredSourceItems.forEach((item) => {
    diagnostics.push(
      articleDiagnostic(
        "sections.sourceCoverage",
        "uncovered_source_item",
        `No section draft reports source coverage item "${item}".`,
        "Add this source coverage item to the appropriate section draft after preserving it in content."
      )
    );
  });

  const ordered = orderedSections(planSectionIds, sections);
  const expressions = ordered.flatMap((section) => section.expressions);
  const blocks = ordered.flatMap((section) => section.blocks);
  const page: InformationStructureHtmlPageInput = {
    title: plan.title,
    description: plan.description ?? plan.brief.purpose,
    structure: plan.targetStructure,
    contentTypes: [plan.targetStructure],
    styleProfile: plan.styleProfile,
    expression: {
      strategy: "auto",
      coreViewpoint: plan.brief.coreViewpoint,
      keyTakeaways: ordered.map((section) => section.summary).filter(Boolean).slice(0, 4)
    },
    expressions,
    blocks,
    footer: {
      text: "Generated by HTML Render MCP article harness"
    }
  };

  const parsedPage = informationStructureHtmlPageSchema.safeParse(page);

  if (!parsedPage.success) {
    parsedPage.error.issues.forEach((issue) => {
      diagnostics.push(
        articleDiagnostic(
          `page.${issue.path.join(".")}`,
          String(issue.code),
          issue.message,
          "Revise section drafts or plan fields so the assembled page matches render_information_structure_html."
        )
      );
    });
  }

  const ok = !hasBlockingDiagnostics(diagnostics);

  return {
    page,
    diagnostics,
    coverageSummary: {
      plannedSections: plan.sections.length,
      receivedSections: sections.length,
      missingSectionIds,
      uncoveredSourceItems
    },
    nextAction: ok ? "validate_html_render_page" : "revise_sections"
  };
}
